Repository CS2103-AY1819S1-T09-2/main, pull requests merged in 2018-10, with the labels that each got.

#20 Update DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#22 [WIP] Implement the Edit Command for Anakin
  src/main/java/seedu/address/logic/commands/AnakinEditCommand.java
Labels: priority.High

#21 Add 8 new classes
  src/main/java/seedu/address/commons/core/Anakin_ComponentManager.java
  src/main/java/seedu/address/commons/events/model/Anakin_AnakinChangedEvent.java
  src/main/java/seedu/address/logic/Anakin_commands/Anakin_Command.java
  src/main/java/seedu/address/logic/Anakin_commands/Anakin_DelDeckCommand.java
  src/main/java/seedu/address/logic/Anakin_commands/Anakin_NewDeckCommand.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Anakin_ModelManager.java
  src/main/java/seedu/address/model/Anakin_VersionedAnakin.java
  src/main/java/seedu/address/model/Anakin_deck/Anakin_Card.java
Labels: priority.High

#25 Fix naming for thanh's picture
  docs/AboutUs.adoc
  docs/images/truongthanh2606.png
Labels: type.Task

#26 Add AnakinListCommand
  src/main/java/seedu/address/logic/Anakin_commands/AnakinListCommand.java
Labels: priority.High

#31 Update CLI syntax with Anakin prefixes
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.High

#30 Update User Guide
  docs/UserGuide.adoc
Labels: type.Task

#35 Fix upstream bug
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: severity.Low, type.Bug

#34 Update User Guide
  docs/UserGuide.adoc
Labels: type.Task

#37 Add Edit Card Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Anakin_commands/AnakinEditCardCommand.java
  src/main/java/seedu/address/model/Anakin_Model.java
  src/main/java/seedu/address/model/Anakin_ModelManager.java
  src/main/java/seedu/address/model/Anakin_deck/AnakinAnswer.java
  src/main/java/seedu/address/model/Anakin_deck/AnakinQuestion.java
  src/main/java/seedu/address/model/Anakin_deck/Anakin_Card.java
Labels: priority.High

#38 [WIP] Change naming convention of files
  src/main/java/seedu/address/commons/core/AnakinComponentManager.java
  src/main/java/seedu/address/commons/events/model/AnakinChangedEvent.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/AnakinModel.java
  src/main/java/seedu/address/model/AnakinModelManager.java
  src/main/java/seedu/address/model/AnakinReadOnlyAnakin.java
  src/main/java/seedu/address/model/AnakinVersionedAnakin.java
Labels: priority.High

#40 Update Anakin, AnakinModelManager add Exception classes
  src/main/java/seedu/address/logic/AnakinCommands/AnakinDelDeckCommand.java
  src/main/java/seedu/address/logic/AnakinCommands/AnakinEditCardCommand.java
  src/main/java/seedu/address/logic/AnakinCommands/AnakinEditDeckCommand.java
  src/main/java/seedu/address/logic/AnakinCommands/AnakinNewDeckCommand.java
  src/main/java/seedu/address/logic/AnakinLogic.java
  src/main/java/seedu/address/logic/AnakinLogicManager.java
  src/main/java/seedu/address/logic/Anakinparser/AnakinNewDeckCommandParser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/AnakinModel.java
  src/main/java/seedu/address/model/AnakinModelManager.java
  src/main/java/seedu/address/model/AnakinReadOnlyAnakin.java
  src/main/java/seedu/address/model/anakindeck/AnakinAnswer.java
  src/main/java/seedu/address/model/anakindeck/AnakinCard.java
  src/main/java/seedu/address/model/anakindeck/AnakinDeck.java
  src/main/java/seedu/address/model/anakindeck/AnakinExceptions/CardNotFoundException.java
  src/main/java/seedu/address/model/anakindeck/AnakinExceptions/DeckNotFoundException.java
  src/main/java/seedu/address/model/anakindeck/AnakinExceptions/DuplicateCardException.java
  src/main/java/seedu/address/model/anakindeck/AnakinExceptions/DuplicateDeckException.java
  src/main/java/seedu/address/model/anakindeck/AnakinQuestion.java
  src/main/java/seedu/address/model/anakindeck/AnakinUniqueCardList.java
  src/main/java/seedu/address/model/anakindeck/AnakinUniqueDeckList.java
  src/main/java/seedu/address/model/anakindeck/Name.java
Labels: priority.Medium

#53 Fix broken imports statements for AnakinParser
  src/main/java/seedu/address/logic/AnakinParser/AnakinParserUtil.java
Labels: priority.High, severity.High

#62 Add CDcommand and supporting files. Modify Model to support
  src/main/java/seedu/address/logic/AnakinCommands/AnakinCdCommand.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinCdCommandParser.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinParser.java
  src/main/java/seedu/address/model/AnakinModel.java
  src/main/java/seedu/address/model/AnakinModelManager.java
Labels: priority.High

#66 Add edit command parser
  src/main/java/seedu/address/logic/AnakinCommands/AnakinEditCardCommand.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinEditCardCommandParser.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinParser.java
Labels: priority.High

#87 Update README and UserGuide
  README.adoc
  docs/UserGuide.adoc
Labels: priority.High

#88 Add unit test for AnakinNewDeckCommand. Create AnakinDeckBuilder.java
  README.adoc
  src/test/java/seedu/address/logic/commands/AnakinNewDeckCommandTest.java
  src/test/java/seedu/address/testutil/AnakinDeckBuilder.java
Labels: priority.High

#113 Update Developer Guide with Architecture and UI
  docs/DeveloperGuide.adoc
  docs/images/AnakinUIClassDiagram.png
Labels: priority.High, type.Task

#77 Morph UI and Integrate Anakin components
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/events/ui/CardPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/DeckPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/AnakinLogic.java
  src/main/java/seedu/address/logic/AnakinLogicManager.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinNewDeckCommandParser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/AnakinModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/anakindeck/AnakinUniqueCardList.java
  src/main/java/seedu/address/model/util/AnakinSampleDataUtil.java
  src/main/java/seedu/address/ui/CardCard.java
  src/main/java/seedu/address/ui/CardListPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/DeckCard.java
  src/main/java/seedu/address/ui/DeckListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/anakin.png
  src/main/resources/view/CardListCard.fxml
  src/main/resources/view/CardListPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeckListCard.fxml
  src/main/resources/view/DeckListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.High, type.Task

#116 Fix package names for select command
  src/main/java/seedu/address/logic/AnakinCommands/AnakinSelectCardCommand.java
  src/main/java/seedu/address/logic/AnakinParser/AnakinSelectCardCommandParser.java
Labels: type.Bug

#118 Update docs for v1.2
  docs/DeveloperGuide.adoc
Labels: type.Task

#122 Add 4 classes for testutil
  src/main/java/seedu/address/model/anakindeck/Name.java
  src/test/java/seedu/address/model/anakindeck/AnakinDeckNameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/anakindeck/NameTest.java
  src/test/java/seedu/address/testutil/AnakinCardBuilder.java
  src/test/java/seedu/address/testutil/AnakinDeckBuilder.java
  src/test/java/seedu/address/testutil/AnakinTypicalCards.java
  src/test/java/seedu/address/testutil/AnakinTypicalDecks.java
Labels: priority.Medium

#128 Fix repourl
  docs/DeveloperGuide.adoc
Labels: type.Bug

#130 Add all unit tests for Model Component
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AnakinModelClassDiagram.png
  docs/images/NewCard sequence diagram.png
  docs/images/NewcardSequenceDiagram.png
  src/main/java/seedu/address/logic/anakincommands/AnakinSortCommand.java
  src/main/java/seedu/address/logic/anakinparser/AnakinParser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/AnakinModel.java
  src/main/java/seedu/address/model/AnakinModelManager.java
  src/main/java/seedu/address/model/anakindeck/AnakinQuestion.java
  src/main/java/seedu/address/model/anakindeck/AnakinUniqueCardList.java
  src/main/java/seedu/address/model/anakindeck/AnakinUniqueDeckList.java
  src/test/java/seedu/address/logic/commands/AnakinCdCommandTest.java
  src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/AnakinNewDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/AnakinSortCommandTest.java
  src/test/java/seedu/address/model/AnakinModelManagerTest.java
  src/test/java/seedu/address/model/AnakinTest.java
  src/test/java/seedu/address/model/VersionedAnakinTest.java
  src/test/java/seedu/address/model/anakindeck/AnakinAnswerTest.java
  src/test/java/seedu/address/model/anakindeck/AnakinQuestionTest.java
  src/test/java/seedu/address/model/anakindeck/CardTest.java
  src/test/java/seedu/address/model/anakindeck/DeckTest.java
  src/test/java/seedu/address/model/anakindeck/UniqueCardListTest.java
  src/test/java/seedu/address/model/anakindeck/UniqueDeckListTest.java
  src/test/java/seedu/address/testutil/AnakinBuilder.java
  src/test/java/seedu/address/testutil/AnakinDeckBuilder.java
Labels: priority.High

#132 Add Undo and Redo commands
  src/main/java/seedu/address/logic/anakincommands/AnakinRedoCommand.java
  src/main/java/seedu/address/logic/anakincommands/AnakinUndoCommand.java
  src/test/java/seedu/address/logic/commands/AnakinRedoCommandTest.java
  src/test/java/seedu/address/logic/commands/AnakinUndoCommandTest.java
Labels: priority.High

#137 Implement UI tests
  src/main/java/seedu/address/model/anakindeck/AnakinQuestion.java
  src/main/java/seedu/address/model/util/AnakinSampleDataUtil.java
  src/main/java/seedu/address/ui/CardCard.java
  src/main/java/seedu/address/ui/DeckCard.java
  src/test/java/guitests/guihandles/CardCardHandle.java
  src/test/java/guitests/guihandles/CardListPanelHandle.java
  src/test/java/guitests/guihandles/DeckCardHandle.java
  src/test/java/guitests/guihandles/DeckListPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/CardCardTest.java
  src/test/java/seedu/address/ui/CardListPanelTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/DeckCardTest.java
  src/test/java/seedu/address/ui/DeckListPanelTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High, type.Test

#135 Fix CdCommand
  src/main/java/seedu/address/logic/anakincommands/AnakinCdCommand.java
Labels: priority.High, severity.Low, type.Bug

#136 Card Create/Delete unit tests
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/AnakinReadOnlyAnakin.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AnakinDelCardCommandTest.java
  src/test/java/seedu/address/logic/commands/AnakinNewCardCommandTest.java
  src/test/java/seedu/address/model/AnakinTest.java
  src/test/java/seedu/address/testutil/AnakinTypicalDecks.java
  src/test/java/seedu/address/testutil/AnakinTypicalIndexes.java
Labels: priority.High, type.Test

#140 Add 7 CommandParser tests
  src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AnakinCdCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinCommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/AnakinDelCardCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinDelDeckCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinEditCardParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinEditDeckParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinNewCardCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AnakinNewDeckCommandParserTest.java
  src/test/java/seedu/address/testutil/EditCardDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditDeckDescriptorBuilder.java
Labels: priority.High, type.Test

#121 Add initial AnakinEditDeck tests
  src/main/java/seedu/address/logic/anakincommands/AnakinEditDeckCommand.java
  src/test/java/seedu/address/logic/commands/AnakinCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/AnakinEditDeckCommandTest.java
  src/test/java/seedu/address/testutil/EditDeckDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Test

#144 Add EditCardCommand test
  src/test/java/seedu/address/logic/commands/AnakinEditCardCommandTest.java
Labels: priority.High, type.Test

#159 Add FindCommand and tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/CardQuestionContainsKeywordsPredicate.java
  src/test/data/XmlSerializableAnakinTest/typicalDecksAnakin.xml
  src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/testutil/TypicalCards.java
  src/test/java/seedu/address/testutil/TypicalDecks.java
Labels: priority.High

#164 Fix bugs #126, #161, update UserGuide and DeveloperGuide
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/model/Anakin.java
  src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.Medium, type.Bug

#168 Fix bugs related to import deck command
  src/main/java/seedu/address/logic/commands/ImportDeckCommand.java
  src/main/java/seedu/address/logic/parser/ImportDeckCommandParser.java
  src/main/java/seedu/address/storage/portmanager/PortManager.java
Labels: priority.Medium, type.Bug

#170 Fix import exceptions
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/logic/commands/ImportDeckCommand.java
  src/main/java/seedu/address/logic/commands/NewDeckCommand.java
  src/main/java/seedu/address/logic/parser/EditDeckCommandParser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/storage/portmanager/PortManager.java
  src/test/java/seedu/address/logic/commands/AddDeckIntegrationTest.java
  src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/logic/parser/EditDeckParserTest.java
  src/test/java/seedu/address/logic/parser/ExportDeckCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ImportDeckCommandParserTest.java
Labels: priority.High, type.Bug

#171 Resolve issue #162, add list command, update exceptions thrown with cards operation
  src/main/java/seedu/address/logic/commands/DeleteCardCommand.java
  src/main/java/seedu/address/logic/commands/EditCardCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NewCardCommand.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/portmanager/PortManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
Labels: priority.High, type.Bug, type.Enhancement

#178 Add ability to review decks
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/EndReviewRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/FlipCardRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ReviewNextCardEvent.java
  src/main/java/seedu/address/commons/events/ui/ReviewPreviousCardEvent.java
  src/main/java/seedu/address/commons/events/ui/StartReviewRequestEvent.java
  src/main/java/seedu/address/logic/commands/EndReviewCommand.java
  src/main/java/seedu/address/logic/commands/FlipCardCommand.java
  src/main/java/seedu/address/logic/commands/NextCardCommand.java
  src/main/java/seedu/address/logic/commands/PreviousCardCommand.java
  src/main/java/seedu/address/logic/commands/ReviewCommand.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ReviewCommandParser.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAnakin.java
  src/main/java/seedu/address/model/deck/UniqueCardList.java
  src/main/java/seedu/address/model/deck/anakinexceptions/IllegalOperationWhileReviewingDeckException.java
  src/main/java/seedu/address/model/deck/anakinexceptions/NotReviewingDeckException.java
  src/main/java/seedu/address/ui/DeckEditScreen.java
  src/main/java/seedu/address/ui/DeckReviewCard.java
  src/main/java/seedu/address/ui/DeckReviewScreen.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeckEditScreen.fxml
  src/main/resources/view/DeckReviewCard.fxml
  src/main/resources/view/DeckReviewScreen.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/model/AnakinTest.java
  src/test/java/systemtests/AnakinSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High, type.Feature

#179 Fix system tests
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/systemtests/AnakinSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.Medium, type.Test

#182 Fix flipcard behavior
  src/main/java/seedu/address/ui/DeckReviewScreen.java
Labels: severity.High, type.Bug

#184 Update docs
  README.adoc
  docs/UserGuide.adoc
Labels: type.Task
