Repository CS2103-AY1819S1-T09-2/main, pull requests merged in 2018-11, with the labels that each got.

#192 Add tests for 4 commands, add project portfolio
  docs/team/truongthanh.adoc
  src/main/java/seedu/address/logic/commands/SelectCardCommand.java
  src/main/java/seedu/address/logic/parser/SelectCardCommandParser.java
  src/test/java/seedu/address/logic/commands/EndReviewCommandTest.java
  src/test/java/seedu/address/logic/commands/NextCardCommandTest.java
  src/test/java/seedu/address/logic/commands/PreviousCardCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewCommandTest.java
Labels: priority.Medium

#201 Fix undo-cd bug
  1a.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lessthanfree.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAnakin.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/storage/portmanager/PortManager.java
  src/test/java/seedu/address/logic/commands/EditCardCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/model/AnakinTest.java
Labels: priority.High, type.Bug

#209 Change the logic of executing commands
  src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCardCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeckCommand.java
  src/main/java/seedu/address/logic/commands/EditCardCommand.java
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/logic/commands/ExportDeckCommand.java
  src/main/java/seedu/address/logic/commands/NewCardCommand.java
  src/main/java/seedu/address/logic/commands/ReviewCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAnakin.java
  src/main/java/seedu/address/model/deck/UniqueCardList.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/test/data/PortManagerTest/Valid Exported Deck.xml
  src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCardCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCardCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/model/AnakinTest.java
Labels: priority.High, type.Epic

#218 Resolve issues #211, #212, #213, #214, #217
  docs/UserGuide.adoc
  docs/team/truongthanh2606.adoc
Labels: priority.Low, type.Bug

#243 Update message for `redo`, resolve issue #219
  docs/team/truongthanh2606.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeDeckCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/model/Anakin.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAnakin.java
  src/main/java/seedu/address/model/VersionedAnakin.java
  src/main/java/seedu/address/model/deck/Card.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/UniqueCardList.java
  src/main/java/seedu/address/model/deck/UniqueDeckList.java
  src/test/data/PortManagerTest/Valid Exported Deck.xml
  src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCardCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCardCommandTest.java
  src/test/java/seedu/address/logic/commands/NewDeckCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#247 Update user guide, project portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/truongthanh2606.adoc
Labels: priority.Low

#240 Add Parser integration test and Several Parser unit tests
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/ClassifyCommand.java
  src/main/java/seedu/address/logic/parser/ChangeDeckCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ClassifyCardParserTest.java
  src/test/java/seedu/address/logic/parser/ParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ReviewCommandParserTest.java
Labels: priority.Medium, type.Test

#250 Add more tests to increase coverage
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/DeckReviewCardHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/ClassifyCommandTest.java
  src/test/java/seedu/address/logic/commands/FlipCardCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDecks.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/DeckReviewCardTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AnakinSystemTest.java
Labels: type.Test

#255 Add tests
  src/main/java/seedu/address/model/Anakin.java
  src/test/java/seedu/address/logic/commands/ChangeDeckCommandTest.java
Labels: priority.Medium, type.Enhancement

#244 Add system tests for edit deck command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditDeckCommand.java
  src/main/java/seedu/address/logic/parser/Autocompleter.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/TypicalDecks.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.Medium, type.Test

#258 Resolve issue #228 #249
  docs/UserGuide.adoc
  docs/team/truongthanh2606.adoc
  src/main/java/seedu/address/logic/commands/ClassifyCommand.java
  src/main/java/seedu/address/logic/commands/EndReviewCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ClassifyCommandTest.java
  src/test/java/seedu/address/logic/commands/EndReviewCommandTest.java
Labels: priority.High, type.Bug

#263 Enhance documents for PPP
  Geography.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AnakinLogicClassDiagram.png
  docs/images/exportScreenshot1.png
  docs/images/exportScreenshot2.png
  docs/images/exportScreenshot3.png
  docs/images/importScreenshot1.png
  docs/images/importScreenshot2.png
  docs/team/lessthanfree.adoc
Labels: type.Task

#264 Edit PPP
  docs/team/lessthanfree.adoc
Labels: type.Task

#274 Fix image not shown bug
  docs/DeveloperGuide.adoc
  docs/images/NewCardSequenceDiagram.png
  docs/team/truongthanh2606.adoc
Labels: type.Bug
